### ISSUE TITLE
Function to return a [(pattern, pattern_line), ...] list when given a song_line

### ISSUE THREAD

**Issue by jhw** [metrasynth/radiant-voices#14]
Hi, is there any functionality in here for parsing the structure of the timeline ? Obviously I can get all the patterns, but trying to find which patterns are played simultaneously during the timeline - thx

**Comment by jhw** [comment]
Thinking about this some more, am guessing the timeline structure is implicit in the shape of `project.patterns`; back to the drawing board

**Comment by gldnspud** [comment]
@jhw I'll respond even though you closed the issue since it's a valid question.

Although it's on my mental wish list, you have indeed found that there is no functionality in Radiant Voices to interpret the patterns as a generalized X/Y space, or to iterate through lines to determine which notes are associated with a given global line number.

Currently, patterns are kept in no particular order, and just keep track of their X/Y position individually. This mirrors how the patterns are written to disk.

As far as how SunVox does things, patterns are sorted and locked from X/Y movement or resizing (only notes are editable) during playback.

A version of its sorting algorithm is here, if you're curious. Not sure how it would translate to your needs though: https://github.com/warmplace/sunvox_sources/blob/master/sunvox_engine/sunvox_engine.cpp#L975

**Comment by gldnspud** [comment]
@jhw I'm going to reopen this since I think it would be useful.

If you end up with some code that works, feel free to post it here and I can help merge it in, or open a PR if you'd like to go that route.

Otherwise, when I find a few moments I'll give it a try and see if I can find something that can perform reasonably for "what's playing at this line"?

**Comment by jhw** [comment]
That's a shame. I'm interested in a 'decompiler' function that takes an
editing project and splits out the separate 'chains' of modules, as each
chain typically represents a specific instrument or sound. Then you want
the patterns associated with each chain. Problem is that you might have
(say) a generator connected to a filter; a  generator pattern might be
playing a single note repeatedly whilst a filter pattern might by varying
the cutoff. You really need to know these two patterns are stacked in the
timeline to be able to get the full sound effect. Otherwise you're left to
infer that two patterns have note entries at the same time periods; or that
a filter pattern is always played in conjunction with a generator pattern
etc. Just a thought

**Comment by gldnspud** [comment]
@jhw I just added a function that will let you iterate through lines of a project and get information about active patterns for that line.

Example usage:

```python
import rv.api
p = rv.api.read_sunvox_file('pixel_cave.sunvox')
L = list([active for line, active in p.pattern_lines()])
L[42]  
  # => 
  # [PatternLine(index=76, source=76, line=42), 
  #  PatternLine(index=32, source=32, line=10)]
```

Does this help you get closer to the analysis you want to perform? Let me know if there are other helper methods I could implement for that. What you're doing sounds really interesting!

**Comment by jhw** [comment]
Thank u, sounds great, will check.

In general I wondered if if could somehow be made more Python 2.7 friendly, yes I am still on Python 2.7 and found Python3 a bit of a pain. Had problems getting all the deps to work, in particular slugify, is it really needed ? In the end I cloned the project and just manually commented out all the slugify refs. In the interest of making it work in as many places as possible I would tend to try and reduce the number of deps to a minimum, esp if they are only doing logging work. Otherwise I would prefer if it was more functional in style, not mad keen on object orientation everything .. but not really complaining, u seem to have done a good job mapping the .IFF format, most things seem to work so far.

So I am not doing anything that interesting other than "trying to make some decent sounding computer music with minimal effort". IMO for most of the stuff out there either the interface sucks or the sound sucks. Am experimenting with connecting Sonic Pi (http://sonic-pi.net/) (whose interface I like but native sound not that great) with Sunvox via MIDI (I love the Sunvox sound but frankly think the tracker sucks); creating Sunvox files from scratch is another area for experimentation.

I will share if I come up with anything interesting but for now just experimenting 

Rgds -

**Comment by gldnspud** [comment]
I have pretty much embraced Python 3 since version 3.5, and it seems that the overall Python community has crossed that threshold as well. It's always going to be a little complicated, I think. But considering frameworks like Django are adopting Python 3, I personally think it's worth it to have gone through the migration pain. 

See also https://www.jetbrains.com/research/devecosystem-2017/python/ and https://rushter.com/blog/python-3-adoption/.

If you want to contribute a patch that uses [six](https://pypi.python.org/pypi/six) to allow use in Python 2.7, I'd love to review and merge it.

About `slugify`, I think you're right that the way we use it in one place could be simplified and inlined. I've added an issue for this: metrasynth/radiant-voices#15

Regarding OO vs Functional approach, I agree. The [radiant-voices-js](/metrasynth/radiant-voices-js/) port is under way, and makes use of [immutable](https://facebook.github.io/immutable-js/) for all of its data structures. Having already done the hard work of documenting the file format, the port to JS/ES6 has been going pretty smoothly when I can find time to work on it.

There's also metrasynth/radiant-voices#8 to update the Python version to use [Pyrsistent](https://pypi.python.org/pypi/pyrsistent) but that probably won't happen until the JS version settles down a bit, since I want to find a language-independent way to address objects in a SunVox project, and to express state change operations.

Finally, be sure to also check out [Solar Sails](http://solar-sails.readthedocs.io/en/latest/) as it features the "MetaModule Construction Kit" (MMCK) which is a self-contained environment for creating, auditioning, tweaking, and finally exporting SunVox synths and projects. I still need to finish some docs about the scripting part of it, but there are several examples in the [Metrasynth gallery](/metrasynth/gallery/).

**Comment by jhw** [comment]
Why are u rewriting in JS ? Why not stick to improving the Python version ?

**Comment by gldnspud** [comment]
I have been improving the Python version. :smile_cat: 

There are a few reasons I chose to rewrite in JS alongside maintaining the current Python work:

1. Some aspects of ES6 orient themselves toward functional programming more than Python. I like anonymous functions with lexical binding. Python tolerates them with `lambda`, ES6 embraces them with `=>`.

2. There was already an [Ableton Link interface](https://github.com/2bbb/node-abletonlink) for Node, and at the time there wasn't for Python. [Now there is](https://github.com/bdyetton/LinkToPy) though and I'm excited to play with it now that I am aware of its existence!

3. I want to learn ES6 more in depth, and this seemed like good practice.

4. I like using React for creating user interfaces, so I want to be able to use Electron to provide a React-driven UI that interacts with the [SunVox library](https://github.com/metrasynth/sunvox-dll-node).

5. I want to be able to distribute Solar Sails as a pure web app once the [SunVox JS player](http://warmplace.ru/soft/sunvox/jsplay/) becomes practical.

**Comment by gldnspud** [comment]
(Closing this particular issue, but willing to continue general discussion here if you like)

**Comment by jhw** [comment]
Have u made much progress on the JS version?

**Comment by jhw** [comment]
Hi, sorry for long delay in replying. Am playing with radiant-voices again,
managed to get Python3.5 installation working using virtualenv, having some
fun with it :-) Is a good project. I will probably have a few issues to if
you could watch Github issues and possibly comment when u have a second
that would be great. Many thanks and hope you are doing well.

**Comment by gldnspud** [comment]
No, these projects have been paused on my side due to personal availability issues.

I do plan on updating the Python version to reflect any changes in the upcoming SunVox 1.9.4 release, but more work on the JS version will have to come some time later.
